# Generated by Django 5.2.1 on 2025-08-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
